const stockOptions = [
    { value: 'AAPL', label: 'Apple - AAPL' },
    { value: 'MSFT', label: 'Microsoft - MSFT' },
    { value: 'AMZN', label: 'Amazon - AMZN' },
    { value: 'GOOG', label: 'Google - GOOG' },
    { value: 'META', label: 'Facebook - META' },
    { value: 'TSLA', label: 'Tesla - TSLA' },
    { value: 'BRK.B', label: 'Berkshire Hathaway - BRK.B' },
    { value: 'V', label: 'Visa - V' },
    { value: 'JNJ', label: 'Johnson & Johnson - JNJ' },
    { value: 'WMT', label: 'Walmart - WMT' },
    { value: 'JPM', label: 'JPMorgan Chase - JPM' },
    { value: 'PG', label: 'Procter & Gamble - PG' },
    { value: 'XOM', label: 'Exxon Mobil - XOM' },
    { value: 'BA', label: 'Boeing - BA' },
    { value: 'BABA', label: 'Alibaba - BABA' },
    { value: 'DIS', label: 'Disney - DIS' },
    { value: 'NVDA', label: 'NVIDIA - NVDA' },
    { value: 'NFLX', label: 'Netflix - NFLX' },
    { value: 'HD', label: 'Home Depot - HD' },
    { value: 'KO', label: 'Coca Cola - KO' },
    { value: 'MA', label: 'Mastercard - MA' },
    { value: 'INTC', label: 'Intel - INTC' },
    { value: 'VZ', label: 'Verizon - VZ' },
    { value: 'UNH', label: 'UnitedHealth Group - UNH' },
    { value: 'PFE', label: 'Pfizer - PFE' },
    { value: 'MRK', label: 'Merck - MRK' },
    { value: 'PEP', label: 'PepsiCo - PEP' },
    { value: 'CVS', label: 'CVS Health - CVS' },
    { value: 'CMCSA', label: 'Comcast - CMCSA' },
    { value: 'BAC', label: 'Bank of America - BAC' },
    { value: 'ADBE', label: 'Adobe - ADBE' },
    { value: 'C', label: 'Citigroup - C' },
    { value: 'ORCL', label: 'Oracle - ORCL' },
    { value: 'PYPL', label: 'Paypal - PYPL' },
    { value: 'IBM', label: 'IBM - IBM' },
    { value: 'MCD', label: 'McDonald\'s - MCD' },
    { value: 'T', label: 'AT&T - T' },
    { value: 'ABBV', label: 'AbbVie - ABBV' },
    { value: 'ACN', label: 'Accenture - ACN' },
    { value: 'ABT', label: 'Abbott Laboratories - ABT' },
    { value: 'CRM', label: 'Salesforce - CRM' },
    { value: 'DVN', label: 'Devon Energy Corp - DVN' },
    { value: 'MRO', label: 'Marathon Oil Corp - MRO' },
    { value: 'MRNA', label: 'Moderna Inc - MRNA' },
    { value: 'FTNT', label: 'Fortinet Inc - FTNT' },
    { value: 'SBNY', label: 'Signature Bank - SBNY' },
    { value: 'F', label: 'Ford Motor Co - F' },
    { value: 'BBWI', label: 'Bath & Body Works Inc - BBWI' },
    { value: 'FANG', label: 'Diamondback Energy Inc - FANG' },
    { value: 'NUE', label: 'Nucor Corp - NUE' },
    { value: 'IT', label: 'Gartner Inc - IT' },
    { value: 'EXR', label: 'Extra Space Storage Inc - EXR' },
    { value: 'ANET', label: 'Arista Networks Inc - ANET' },
    { value: 'SPG', label: 'Simon Property Group Inc - SPG' },
    { value: 'APA', label: 'APA Corp - APA' },
    { value: 'EOG', label: 'EOG Resources Inc - EOG' },
    { value: 'IRM', label: 'Iron Mountain Inc - IRM' },
    { value: 'STX', label: 'Seagate Technology Holdings PLC - STX' },
    { value: 'CF', label: 'CF Industries Holdings Inc - CF' },
    { value: 'COP', label: 'ConocoPhillips - COP' },
    { value: 'GME', label: 'GameStop Corp - GME' }
];
